apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  labels:
    app: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
        - name: app1
          image: 304520711562.dkr.ecr.us-east-1.amazonaws.com/app1:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080